#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Generate background grid with blockMesh
runApplication blockMesh

# Decompose case for parallel grid generation
runApplication decomposePar

# Generate grid in parallel using 4 cores
runParallel snappyHexMesh 4 -overwrite

#- For non-parallel running
#cp -r 0.org 0 > /dev/null 2>&1

#- For parallel running
ls -d processor* | xargs -I {} rm -rf ./{}/0
ls -d processor* | xargs -I {} cp -r 0.org ./{}/0

runParallel $(getApplication) 4

runApplication reconstructParMesh -constant
runApplication reconstructPar -latestTime
runApplication yPlusRAS -latestTime

# ----------------------------------------------------------------- end-of-file
